server:
  port: 8080
  servlet:
    context-path: "/api"
#######datasoure config##############
spring:
  datasource:
    name: work_train
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
    username: root
    password: root
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
#######mybatis config##############
mybatis:
  mapper-locations: classpath:mapper/*.xml
